// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protobuf/clusrun.proto

package clusrun

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type NodeState int32

const (
	NodeState_Unknown NodeState = 0
	NodeState_Ready   NodeState = 1
	NodeState_Error   NodeState = 2
	NodeState_Lost    NodeState = 3
)

var NodeState_name = map[int32]string{
	0: "Unknown",
	1: "Ready",
	2: "Error",
	3: "Lost",
}

var NodeState_value = map[string]int32{
	"Unknown": 0,
	"Ready":   1,
	"Error":   2,
	"Lost":    3,
}

func (x NodeState) String() string {
	return proto.EnumName(NodeState_name, int32(x))
}

func (NodeState) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_1a8110e89f4086ed, []int{0}
}

type JobState int32

const (
	JobState_Created     JobState = 0
	JobState_Dispatching JobState = 1
	JobState_Running     JobState = 2
	JobState_Canceling   JobState = 3
	JobState_Finished    JobState = 4
	JobState_Failed      JobState = 5
	JobState_Canceled    JobState = 6
)

var JobState_name = map[int32]string{
	0: "Created",
	1: "Dispatching",
	2: "Running",
	3: "Canceling",
	4: "Finished",
	5: "Failed",
	6: "Canceled",
}

var JobState_value = map[string]int32{
	"Created":     0,
	"Dispatching": 1,
	"Running":     2,
	"Canceling":   3,
	"Finished":    4,
	"Failed":      5,
	"Canceled":    6,
}

func (x JobState) String() string {
	return proto.EnumName(JobState_name, int32(x))
}

func (JobState) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_1a8110e89f4086ed, []int{1}
}

type HeartbeatRequest struct {
	Nodename             string   `protobuf:"bytes,1,opt,name=nodename,proto3" json:"nodename,omitempty"`
	Host                 string   `protobuf:"bytes,2,opt,name=host,proto3" json:"host,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HeartbeatRequest) Reset()         { *m = HeartbeatRequest{} }
func (m *HeartbeatRequest) String() string { return proto.CompactTextString(m) }
func (*HeartbeatRequest) ProtoMessage()    {}
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1a8110e89f4086ed, []int{0}
}

func (m *HeartbeatRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HeartbeatRequest.Unmarshal(m, b)
}
func (m *HeartbeatRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HeartbeatRequest.Marshal(b, m, deterministic)
}
func (m *HeartbeatRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HeartbeatRequest.Merge(m, src)
}
func (m *HeartbeatRequest) XXX_Size() int {
	return xxx_messageInfo_HeartbeatRequest.Size(m)
}
func (m *HeartbeatRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HeartbeatRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HeartbeatRequest proto.InternalMessageInfo

func (m *HeartbeatRequest) GetNodename() string {
	if m != nil {
		return m.Nodename
	}
	return ""
}

func (m *HeartbeatRequest) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_1a8110e89f4086ed, []int{1}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type GetNodesRequest struct {
	Pattern              string    `protobuf:"bytes,1,opt,name=pattern,proto3" json:"pattern,omitempty"`
	Groups               []string  `protobuf:"bytes,2,rep,name=groups,proto3" json:"groups,omitempty"`
	State                NodeState `protobuf:"varint,3,opt,name=state,proto3,enum=clusrun.NodeState" json:"state,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GetNodesRequest) Reset()         { *m = GetNodesRequest{} }
func (m *GetNodesRequest) String() string { return proto.CompactTextString(m) }
func (*GetNodesRequest) ProtoMessage()    {}
func (*GetNodesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1a8110e89f4086ed, []int{2}
}

func (m *GetNodesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetNodesRequest.Unmarshal(m, b)
}
func (m *GetNodesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetNodesRequest.Marshal(b, m, deterministic)
}
func (m *GetNodesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetNodesRequest.Merge(m, src)
}
func (m *GetNodesRequest) XXX_Size() int {
	return xxx_messageInfo_GetNodesRequest.Size(m)
}
func (m *GetNodesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetNodesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetNodesRequest proto.InternalMessageInfo

func (m *GetNodesRequest) GetPattern() string {
	if m != nil {
		return m.Pattern
	}
	return ""
}

func (m *GetNodesRequest) GetGroups() []string {
	if m != nil {
		return m.Groups
	}
	return nil
}

func (m *GetNodesRequest) GetState() NodeState {
	if m != nil {
		return m.State
	}
	return NodeState_Unknown
}

type GetNodesReply struct {
	Nodes                []*GetNodesReply_Node `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *GetNodesReply) Reset()         { *m = GetNodesReply{} }
func (m *GetNodesReply) String() string { return proto.CompactTextString(m) }
func (*GetNodesReply) ProtoMessage()    {}
func (*GetNodesReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_1a8110e89f4086ed, []int{3}
}

func (m *GetNodesReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetNodesReply.Unmarshal(m, b)
}
func (m *GetNodesReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetNodesReply.Marshal(b, m, deterministic)
}
func (m *GetNodesReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetNodesReply.Merge(m, src)
}
func (m *GetNodesReply) XXX_Size() int {
	return xxx_messageInfo_GetNodesReply.Size(m)
}
func (m *GetNodesReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetNodesReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetNodesReply proto.InternalMessageInfo

func (m *GetNodesReply) GetNodes() []*GetNodesReply_Node {
	if m != nil {
		return m.Nodes
	}
	return nil
}

type GetNodesReply_Node struct {
	Name                 string    `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	State                NodeState `protobuf:"varint,2,opt,name=state,proto3,enum=clusrun.NodeState" json:"state,omitempty"`
	Jobs                 []int32   `protobuf:"varint,3,rep,packed,name=jobs,proto3" json:"jobs,omitempty"`
	Groups               []string  `protobuf:"bytes,4,rep,name=groups,proto3" json:"groups,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GetNodesReply_Node) Reset()         { *m = GetNodesReply_Node{} }
func (m *GetNodesReply_Node) String() string { return proto.CompactTextString(m) }
func (*GetNodesReply_Node) ProtoMessage()    {}
func (*GetNodesReply_Node) Descriptor() ([]byte, []int) {
	return fileDescriptor_1a8110e89f4086ed, []int{3, 0}
}

func (m *GetNodesReply_Node) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetNodesReply_Node.Unmarshal(m, b)
}
func (m *GetNodesReply_Node) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetNodesReply_Node.Marshal(b, m, deterministic)
}
func (m *GetNodesReply_Node) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetNodesReply_Node.Merge(m, src)
}
func (m *GetNodesReply_Node) XXX_Size() int {
	return xxx_messageInfo_GetNodesReply_Node.Size(m)
}
func (m *GetNodesReply_Node) XXX_DiscardUnknown() {
	xxx_messageInfo_GetNodesReply_Node.DiscardUnknown(m)
}

var xxx_messageInfo_GetNodesReply_Node proto.InternalMessageInfo

func (m *GetNodesReply_Node) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GetNodesReply_Node) GetState() NodeState {
	if m != nil {
		return m.State
	}
	return NodeState_Unknown
}

func (m *GetNodesReply_Node) GetJobs() []int32 {
	if m != nil {
		return m.Jobs
	}
	return nil
}

func (m *GetNodesReply_Node) GetGroups() []string {
	if m != nil {
		return m.Groups
	}
	return nil
}

type GetJobsRequest struct {
	JobIds               map[int32]bool `protobuf:"bytes,1,rep,name=job_ids,json=jobIds,proto3" json:"job_ids,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *GetJobsRequest) Reset()         { *m = GetJobsRequest{} }
func (m *GetJobsRequest) String() string { return proto.CompactTextString(m) }
func (*GetJobsRequest) ProtoMessage()    {}
func (*GetJobsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1a8110e89f4086ed, []int{4}
}

func (m *GetJobsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetJobsRequest.Unmarshal(m, b)
}
func (m *GetJobsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetJobsRequest.Marshal(b, m, deterministic)
}
func (m *GetJobsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetJobsRequest.Merge(m, src)
}
func (m *GetJobsRequest) XXX_Size() int {
	return xxx_messageInfo_GetJobsRequest.Size(m)
}
func (m *GetJobsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetJobsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetJobsRequest proto.InternalMessageInfo

func (m *GetJobsRequest) GetJobIds() map[int32]bool {
	if m != nil {
		return m.JobIds
	}
	return nil
}

type Job struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Command              string   `protobuf:"bytes,2,opt,name=command,proto3" json:"command,omitempty"`
	Nodes                []string `protobuf:"bytes,3,rep,name=nodes,proto3" json:"nodes,omitempty"`
	CreateTime           int64    `protobuf:"varint,4,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	EndTime              int64    `protobuf:"varint,5,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	State                JobState `protobuf:"varint,6,opt,name=state,proto3,enum=clusrun.JobState" json:"state,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Job) Reset()         { *m = Job{} }
func (m *Job) String() string { return proto.CompactTextString(m) }
func (*Job) ProtoMessage()    {}
func (*Job) Descriptor() ([]byte, []int) {
	return fileDescriptor_1a8110e89f4086ed, []int{5}
}

func (m *Job) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Job.Unmarshal(m, b)
}
func (m *Job) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Job.Marshal(b, m, deterministic)
}
func (m *Job) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Job.Merge(m, src)
}
func (m *Job) XXX_Size() int {
	return xxx_messageInfo_Job.Size(m)
}
func (m *Job) XXX_DiscardUnknown() {
	xxx_messageInfo_Job.DiscardUnknown(m)
}

var xxx_messageInfo_Job proto.InternalMessageInfo

func (m *Job) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Job) GetCommand() string {
	if m != nil {
		return m.Command
	}
	return ""
}

func (m *Job) GetNodes() []string {
	if m != nil {
		return m.Nodes
	}
	return nil
}

func (m *Job) GetCreateTime() int64 {
	if m != nil {
		return m.CreateTime
	}
	return 0
}

func (m *Job) GetEndTime() int64 {
	if m != nil {
		return m.EndTime
	}
	return 0
}

func (m *Job) GetState() JobState {
	if m != nil {
		return m.State
	}
	return JobState_Created
}

type GetJobsReply struct {
	Jobs                 []*Job   `protobuf:"bytes,1,rep,name=jobs,proto3" json:"jobs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetJobsReply) Reset()         { *m = GetJobsReply{} }
func (m *GetJobsReply) String() string { return proto.CompactTextString(m) }
func (*GetJobsReply) ProtoMessage()    {}
func (*GetJobsReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_1a8110e89f4086ed, []int{6}
}

func (m *GetJobsReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetJobsReply.Unmarshal(m, b)
}
func (m *GetJobsReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetJobsReply.Marshal(b, m, deterministic)
}
func (m *GetJobsReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetJobsReply.Merge(m, src)
}
func (m *GetJobsReply) XXX_Size() int {
	return xxx_messageInfo_GetJobsReply.Size(m)
}
func (m *GetJobsReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetJobsReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetJobsReply proto.InternalMessageInfo

func (m *GetJobsReply) GetJobs() []*Job {
	if m != nil {
		return m.Jobs
	}
	return nil
}

type GetOutputRequest struct {
	JobId                int32    `protobuf:"varint,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Node                 string   `protobuf:"bytes,2,opt,name=node,proto3" json:"node,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetOutputRequest) Reset()         { *m = GetOutputRequest{} }
func (m *GetOutputRequest) String() string { return proto.CompactTextString(m) }
func (*GetOutputRequest) ProtoMessage()    {}
func (*GetOutputRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1a8110e89f4086ed, []int{7}
}

func (m *GetOutputRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetOutputRequest.Unmarshal(m, b)
}
func (m *GetOutputRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetOutputRequest.Marshal(b, m, deterministic)
}
func (m *GetOutputRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetOutputRequest.Merge(m, src)
}
func (m *GetOutputRequest) XXX_Size() int {
	return xxx_messageInfo_GetOutputRequest.Size(m)
}
func (m *GetOutputRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetOutputRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetOutputRequest proto.InternalMessageInfo

func (m *GetOutputRequest) GetJobId() int32 {
	if m != nil {
		return m.JobId
	}
	return 0
}

func (m *GetOutputRequest) GetNode() string {
	if m != nil {
		return m.Node
	}
	return ""
}

type GetOutputReply struct {
	Node                 string   `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	Stdout               string   `protobuf:"bytes,2,opt,name=stdout,proto3" json:"stdout,omitempty"`
	Stderr               string   `protobuf:"bytes,3,opt,name=stderr,proto3" json:"stderr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetOutputReply) Reset()         { *m = GetOutputReply{} }
func (m *GetOutputReply) String() string { return proto.CompactTextString(m) }
func (*GetOutputReply) ProtoMessage()    {}
func (*GetOutputReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_1a8110e89f4086ed, []int{8}
}

func (m *GetOutputReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetOutputReply.Unmarshal(m, b)
}
func (m *GetOutputReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetOutputReply.Marshal(b, m, deterministic)
}
func (m *GetOutputReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetOutputReply.Merge(m, src)
}
func (m *GetOutputReply) XXX_Size() int {
	return xxx_messageInfo_GetOutputReply.Size(m)
}
func (m *GetOutputReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetOutputReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetOutputReply proto.InternalMessageInfo

func (m *GetOutputReply) GetNode() string {
	if m != nil {
		return m.Node
	}
	return ""
}

func (m *GetOutputReply) GetStdout() string {
	if m != nil {
		return m.Stdout
	}
	return ""
}

func (m *GetOutputReply) GetStderr() string {
	if m != nil {
		return m.Stderr
	}
	return ""
}

type StartClusJobRequest struct {
	Command              string   `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	Nodes                []string `protobuf:"bytes,2,rep,name=nodes,proto3" json:"nodes,omitempty"`
	Pattern              string   `protobuf:"bytes,3,opt,name=pattern,proto3" json:"pattern,omitempty"`
	Group                string   `protobuf:"bytes,4,opt,name=group,proto3" json:"group,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StartClusJobRequest) Reset()         { *m = StartClusJobRequest{} }
func (m *StartClusJobRequest) String() string { return proto.CompactTextString(m) }
func (*StartClusJobRequest) ProtoMessage()    {}
func (*StartClusJobRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1a8110e89f4086ed, []int{9}
}

func (m *StartClusJobRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StartClusJobRequest.Unmarshal(m, b)
}
func (m *StartClusJobRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StartClusJobRequest.Marshal(b, m, deterministic)
}
func (m *StartClusJobRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartClusJobRequest.Merge(m, src)
}
func (m *StartClusJobRequest) XXX_Size() int {
	return xxx_messageInfo_StartClusJobRequest.Size(m)
}
func (m *StartClusJobRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StartClusJobRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StartClusJobRequest proto.InternalMessageInfo

func (m *StartClusJobRequest) GetCommand() string {
	if m != nil {
		return m.Command
	}
	return ""
}

func (m *StartClusJobRequest) GetNodes() []string {
	if m != nil {
		return m.Nodes
	}
	return nil
}

func (m *StartClusJobRequest) GetPattern() string {
	if m != nil {
		return m.Pattern
	}
	return ""
}

func (m *StartClusJobRequest) GetGroup() string {
	if m != nil {
		return m.Group
	}
	return ""
}

type StartClusJobReply struct {
	JobId                int32    `protobuf:"varint,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Nodes                []string `protobuf:"bytes,2,rep,name=nodes,proto3" json:"nodes,omitempty"`
	Node                 string   `protobuf:"bytes,3,opt,name=node,proto3" json:"node,omitempty"`
	Stdout               string   `protobuf:"bytes,4,opt,name=stdout,proto3" json:"stdout,omitempty"`
	Stderr               string   `protobuf:"bytes,5,opt,name=stderr,proto3" json:"stderr,omitempty"`
	ExitCode             int32    `protobuf:"zigzag32,6,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StartClusJobReply) Reset()         { *m = StartClusJobReply{} }
func (m *StartClusJobReply) String() string { return proto.CompactTextString(m) }
func (*StartClusJobReply) ProtoMessage()    {}
func (*StartClusJobReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_1a8110e89f4086ed, []int{10}
}

func (m *StartClusJobReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StartClusJobReply.Unmarshal(m, b)
}
func (m *StartClusJobReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StartClusJobReply.Marshal(b, m, deterministic)
}
func (m *StartClusJobReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartClusJobReply.Merge(m, src)
}
func (m *StartClusJobReply) XXX_Size() int {
	return xxx_messageInfo_StartClusJobReply.Size(m)
}
func (m *StartClusJobReply) XXX_DiscardUnknown() {
	xxx_messageInfo_StartClusJobReply.DiscardUnknown(m)
}

var xxx_messageInfo_StartClusJobReply proto.InternalMessageInfo

func (m *StartClusJobReply) GetJobId() int32 {
	if m != nil {
		return m.JobId
	}
	return 0
}

func (m *StartClusJobReply) GetNodes() []string {
	if m != nil {
		return m.Nodes
	}
	return nil
}

func (m *StartClusJobReply) GetNode() string {
	if m != nil {
		return m.Node
	}
	return ""
}

func (m *StartClusJobReply) GetStdout() string {
	if m != nil {
		return m.Stdout
	}
	return ""
}

func (m *StartClusJobReply) GetStderr() string {
	if m != nil {
		return m.Stderr
	}
	return ""
}

func (m *StartClusJobReply) GetExitCode() int32 {
	if m != nil {
		return m.ExitCode
	}
	return 0
}

type CancelClusJobRequest struct {
	JobId                int32    `protobuf:"varint,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CancelClusJobRequest) Reset()         { *m = CancelClusJobRequest{} }
func (m *CancelClusJobRequest) String() string { return proto.CompactTextString(m) }
func (*CancelClusJobRequest) ProtoMessage()    {}
func (*CancelClusJobRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1a8110e89f4086ed, []int{11}
}

func (m *CancelClusJobRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CancelClusJobRequest.Unmarshal(m, b)
}
func (m *CancelClusJobRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CancelClusJobRequest.Marshal(b, m, deterministic)
}
func (m *CancelClusJobRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CancelClusJobRequest.Merge(m, src)
}
func (m *CancelClusJobRequest) XXX_Size() int {
	return xxx_messageInfo_CancelClusJobRequest.Size(m)
}
func (m *CancelClusJobRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CancelClusJobRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CancelClusJobRequest proto.InternalMessageInfo

func (m *CancelClusJobRequest) GetJobId() int32 {
	if m != nil {
		return m.JobId
	}
	return 0
}

type StartJobRequest struct {
	Headnode             string   `protobuf:"bytes,1,opt,name=headnode,proto3" json:"headnode,omitempty"`
	JobId                int32    `protobuf:"varint,2,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Command              string   `protobuf:"bytes,3,opt,name=command,proto3" json:"command,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StartJobRequest) Reset()         { *m = StartJobRequest{} }
func (m *StartJobRequest) String() string { return proto.CompactTextString(m) }
func (*StartJobRequest) ProtoMessage()    {}
func (*StartJobRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1a8110e89f4086ed, []int{12}
}

func (m *StartJobRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StartJobRequest.Unmarshal(m, b)
}
func (m *StartJobRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StartJobRequest.Marshal(b, m, deterministic)
}
func (m *StartJobRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartJobRequest.Merge(m, src)
}
func (m *StartJobRequest) XXX_Size() int {
	return xxx_messageInfo_StartJobRequest.Size(m)
}
func (m *StartJobRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StartJobRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StartJobRequest proto.InternalMessageInfo

func (m *StartJobRequest) GetHeadnode() string {
	if m != nil {
		return m.Headnode
	}
	return ""
}

func (m *StartJobRequest) GetJobId() int32 {
	if m != nil {
		return m.JobId
	}
	return 0
}

func (m *StartJobRequest) GetCommand() string {
	if m != nil {
		return m.Command
	}
	return ""
}

type StartJobReply struct {
	Stdout               string   `protobuf:"bytes,1,opt,name=stdout,proto3" json:"stdout,omitempty"`
	Stderr               string   `protobuf:"bytes,2,opt,name=stderr,proto3" json:"stderr,omitempty"`
	ExitCode             int32    `protobuf:"zigzag32,3,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StartJobReply) Reset()         { *m = StartJobReply{} }
func (m *StartJobReply) String() string { return proto.CompactTextString(m) }
func (*StartJobReply) ProtoMessage()    {}
func (*StartJobReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_1a8110e89f4086ed, []int{13}
}

func (m *StartJobReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StartJobReply.Unmarshal(m, b)
}
func (m *StartJobReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StartJobReply.Marshal(b, m, deterministic)
}
func (m *StartJobReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartJobReply.Merge(m, src)
}
func (m *StartJobReply) XXX_Size() int {
	return xxx_messageInfo_StartJobReply.Size(m)
}
func (m *StartJobReply) XXX_DiscardUnknown() {
	xxx_messageInfo_StartJobReply.DiscardUnknown(m)
}

var xxx_messageInfo_StartJobReply proto.InternalMessageInfo

func (m *StartJobReply) GetStdout() string {
	if m != nil {
		return m.Stdout
	}
	return ""
}

func (m *StartJobReply) GetStderr() string {
	if m != nil {
		return m.Stderr
	}
	return ""
}

func (m *StartJobReply) GetExitCode() int32 {
	if m != nil {
		return m.ExitCode
	}
	return 0
}

type CancelJobRequest struct {
	Headnode             string   `protobuf:"bytes,1,opt,name=headnode,proto3" json:"headnode,omitempty"`
	JobId                int32    `protobuf:"varint,2,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Force                bool     `protobuf:"varint,3,opt,name=force,proto3" json:"force,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CancelJobRequest) Reset()         { *m = CancelJobRequest{} }
func (m *CancelJobRequest) String() string { return proto.CompactTextString(m) }
func (*CancelJobRequest) ProtoMessage()    {}
func (*CancelJobRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1a8110e89f4086ed, []int{14}
}

func (m *CancelJobRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CancelJobRequest.Unmarshal(m, b)
}
func (m *CancelJobRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CancelJobRequest.Marshal(b, m, deterministic)
}
func (m *CancelJobRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CancelJobRequest.Merge(m, src)
}
func (m *CancelJobRequest) XXX_Size() int {
	return xxx_messageInfo_CancelJobRequest.Size(m)
}
func (m *CancelJobRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CancelJobRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CancelJobRequest proto.InternalMessageInfo

func (m *CancelJobRequest) GetHeadnode() string {
	if m != nil {
		return m.Headnode
	}
	return ""
}

func (m *CancelJobRequest) GetJobId() int32 {
	if m != nil {
		return m.JobId
	}
	return 0
}

func (m *CancelJobRequest) GetForce() bool {
	if m != nil {
		return m.Force
	}
	return false
}

type ValidateRequest struct {
	Headnode             string   `protobuf:"bytes,1,opt,name=headnode,proto3" json:"headnode,omitempty"`
	Clusnode             string   `protobuf:"bytes,2,opt,name=clusnode,proto3" json:"clusnode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ValidateRequest) Reset()         { *m = ValidateRequest{} }
func (m *ValidateRequest) String() string { return proto.CompactTextString(m) }
func (*ValidateRequest) ProtoMessage()    {}
func (*ValidateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1a8110e89f4086ed, []int{15}
}

func (m *ValidateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValidateRequest.Unmarshal(m, b)
}
func (m *ValidateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValidateRequest.Marshal(b, m, deterministic)
}
func (m *ValidateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidateRequest.Merge(m, src)
}
func (m *ValidateRequest) XXX_Size() int {
	return xxx_messageInfo_ValidateRequest.Size(m)
}
func (m *ValidateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ValidateRequest proto.InternalMessageInfo

func (m *ValidateRequest) GetHeadnode() string {
	if m != nil {
		return m.Headnode
	}
	return ""
}

func (m *ValidateRequest) GetClusnode() string {
	if m != nil {
		return m.Clusnode
	}
	return ""
}

type ValidateReply struct {
	Nodename             string   `protobuf:"bytes,1,opt,name=nodename,proto3" json:"nodename,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ValidateReply) Reset()         { *m = ValidateReply{} }
func (m *ValidateReply) String() string { return proto.CompactTextString(m) }
func (*ValidateReply) ProtoMessage()    {}
func (*ValidateReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_1a8110e89f4086ed, []int{16}
}

func (m *ValidateReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValidateReply.Unmarshal(m, b)
}
func (m *ValidateReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValidateReply.Marshal(b, m, deterministic)
}
func (m *ValidateReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidateReply.Merge(m, src)
}
func (m *ValidateReply) XXX_Size() int {
	return xxx_messageInfo_ValidateReply.Size(m)
}
func (m *ValidateReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidateReply.DiscardUnknown(m)
}

var xxx_messageInfo_ValidateReply proto.InternalMessageInfo

func (m *ValidateReply) GetNodename() string {
	if m != nil {
		return m.Nodename
	}
	return ""
}

type SetHeadnodesRequest struct {
	Headnodes            []string `protobuf:"bytes,1,rep,name=headnodes,proto3" json:"headnodes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetHeadnodesRequest) Reset()         { *m = SetHeadnodesRequest{} }
func (m *SetHeadnodesRequest) String() string { return proto.CompactTextString(m) }
func (*SetHeadnodesRequest) ProtoMessage()    {}
func (*SetHeadnodesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1a8110e89f4086ed, []int{17}
}

func (m *SetHeadnodesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetHeadnodesRequest.Unmarshal(m, b)
}
func (m *SetHeadnodesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetHeadnodesRequest.Marshal(b, m, deterministic)
}
func (m *SetHeadnodesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetHeadnodesRequest.Merge(m, src)
}
func (m *SetHeadnodesRequest) XXX_Size() int {
	return xxx_messageInfo_SetHeadnodesRequest.Size(m)
}
func (m *SetHeadnodesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetHeadnodesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetHeadnodesRequest proto.InternalMessageInfo

func (m *SetHeadnodesRequest) GetHeadnodes() []string {
	if m != nil {
		return m.Headnodes
	}
	return nil
}

type SetHeadnodesReply struct {
	Results              map[string]string `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *SetHeadnodesReply) Reset()         { *m = SetHeadnodesReply{} }
func (m *SetHeadnodesReply) String() string { return proto.CompactTextString(m) }
func (*SetHeadnodesReply) ProtoMessage()    {}
func (*SetHeadnodesReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_1a8110e89f4086ed, []int{18}
}

func (m *SetHeadnodesReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetHeadnodesReply.Unmarshal(m, b)
}
func (m *SetHeadnodesReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetHeadnodesReply.Marshal(b, m, deterministic)
}
func (m *SetHeadnodesReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetHeadnodesReply.Merge(m, src)
}
func (m *SetHeadnodesReply) XXX_Size() int {
	return xxx_messageInfo_SetHeadnodesReply.Size(m)
}
func (m *SetHeadnodesReply) XXX_DiscardUnknown() {
	xxx_messageInfo_SetHeadnodesReply.DiscardUnknown(m)
}

var xxx_messageInfo_SetHeadnodesReply proto.InternalMessageInfo

func (m *SetHeadnodesReply) GetResults() map[string]string {
	if m != nil {
		return m.Results
	}
	return nil
}

type GetHeadnodesReply struct {
	Headnodes            map[string]bool `protobuf:"bytes,1,rep,name=headnodes,proto3" json:"headnodes,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *GetHeadnodesReply) Reset()         { *m = GetHeadnodesReply{} }
func (m *GetHeadnodesReply) String() string { return proto.CompactTextString(m) }
func (*GetHeadnodesReply) ProtoMessage()    {}
func (*GetHeadnodesReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_1a8110e89f4086ed, []int{19}
}

func (m *GetHeadnodesReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetHeadnodesReply.Unmarshal(m, b)
}
func (m *GetHeadnodesReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetHeadnodesReply.Marshal(b, m, deterministic)
}
func (m *GetHeadnodesReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetHeadnodesReply.Merge(m, src)
}
func (m *GetHeadnodesReply) XXX_Size() int {
	return xxx_messageInfo_GetHeadnodesReply.Size(m)
}
func (m *GetHeadnodesReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetHeadnodesReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetHeadnodesReply proto.InternalMessageInfo

func (m *GetHeadnodesReply) GetHeadnodes() map[string]bool {
	if m != nil {
		return m.Headnodes
	}
	return nil
}

func init() {
	proto.RegisterEnum("clusrun.NodeState", NodeState_name, NodeState_value)
	proto.RegisterEnum("clusrun.JobState", JobState_name, JobState_value)
	proto.RegisterType((*HeartbeatRequest)(nil), "clusrun.HeartbeatRequest")
	proto.RegisterType((*Empty)(nil), "clusrun.Empty")
	proto.RegisterType((*GetNodesRequest)(nil), "clusrun.GetNodesRequest")
	proto.RegisterType((*GetNodesReply)(nil), "clusrun.GetNodesReply")
	proto.RegisterType((*GetNodesReply_Node)(nil), "clusrun.GetNodesReply.Node")
	proto.RegisterType((*GetJobsRequest)(nil), "clusrun.GetJobsRequest")
	proto.RegisterMapType((map[int32]bool)(nil), "clusrun.GetJobsRequest.JobIdsEntry")
	proto.RegisterType((*Job)(nil), "clusrun.Job")
	proto.RegisterType((*GetJobsReply)(nil), "clusrun.GetJobsReply")
	proto.RegisterType((*GetOutputRequest)(nil), "clusrun.GetOutputRequest")
	proto.RegisterType((*GetOutputReply)(nil), "clusrun.GetOutputReply")
	proto.RegisterType((*StartClusJobRequest)(nil), "clusrun.StartClusJobRequest")
	proto.RegisterType((*StartClusJobReply)(nil), "clusrun.StartClusJobReply")
	proto.RegisterType((*CancelClusJobRequest)(nil), "clusrun.CancelClusJobRequest")
	proto.RegisterType((*StartJobRequest)(nil), "clusrun.StartJobRequest")
	proto.RegisterType((*StartJobReply)(nil), "clusrun.StartJobReply")
	proto.RegisterType((*CancelJobRequest)(nil), "clusrun.CancelJobRequest")
	proto.RegisterType((*ValidateRequest)(nil), "clusrun.ValidateRequest")
	proto.RegisterType((*ValidateReply)(nil), "clusrun.ValidateReply")
	proto.RegisterType((*SetHeadnodesRequest)(nil), "clusrun.SetHeadnodesRequest")
	proto.RegisterType((*SetHeadnodesReply)(nil), "clusrun.SetHeadnodesReply")
	proto.RegisterMapType((map[string]string)(nil), "clusrun.SetHeadnodesReply.ResultsEntry")
	proto.RegisterType((*GetHeadnodesReply)(nil), "clusrun.GetHeadnodesReply")
	proto.RegisterMapType((map[string]bool)(nil), "clusrun.GetHeadnodesReply.HeadnodesEntry")
}

func init() { proto.RegisterFile("protobuf/clusrun.proto", fileDescriptor_1a8110e89f4086ed) }

var fileDescriptor_1a8110e89f4086ed = []byte{
	// 1092 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x56, 0x41, 0x93, 0xdb, 0x34,
	0x14, 0x8e, 0xed, 0x38, 0xb1, 0x5f, 0xb2, 0x59, 0xaf, 0xba, 0xdd, 0x66, 0xdd, 0x32, 0x64, 0xcc,
	0xa1, 0xa1, 0x0c, 0x4b, 0x49, 0x2f, 0x4b, 0x59, 0x98, 0x42, 0xd8, 0xa6, 0xcd, 0x74, 0x60, 0xc6,
	0x5b, 0xb8, 0xc0, 0xb0, 0xe3, 0xc4, 0x6a, 0xd7, 0xdb, 0xc4, 0x0a, 0xb6, 0x0c, 0xe4, 0x27, 0x70,
	0xe5, 0xc0, 0x81, 0x1b, 0x57, 0xce, 0xfc, 0x10, 0x7e, 0x12, 0x23, 0xc9, 0xb2, 0x65, 0x27, 0x69,
	0x99, 0xe9, 0x4d, 0x4f, 0x4f, 0xef, 0xe9, 0x7d, 0xdf, 0xd3, 0x7b, 0x4f, 0x70, 0xb4, 0x4a, 0x08,
	0x25, 0xb3, 0xec, 0xc5, 0x47, 0xf3, 0x45, 0x96, 0x26, 0x59, 0x7c, 0xc2, 0x37, 0x50, 0x3b, 0x17,
	0xbd, 0x2f, 0xc1, 0x79, 0x82, 0x83, 0x84, 0xce, 0x70, 0x40, 0x7d, 0xfc, 0x53, 0x86, 0x53, 0x8a,
	0x5c, 0xb0, 0x62, 0x12, 0xe2, 0x38, 0x58, 0xe2, 0xbe, 0x36, 0xd0, 0x86, 0xb6, 0x5f, 0xc8, 0x08,
	0x41, 0xf3, 0x8a, 0xa4, 0xb4, 0xaf, 0xf3, 0x7d, 0xbe, 0xf6, 0xda, 0x60, 0x9e, 0x2f, 0x57, 0x74,
	0xed, 0x2d, 0x61, 0x7f, 0x82, 0xe9, 0xd7, 0x24, 0xc4, 0xa9, 0xf4, 0xd5, 0x87, 0xf6, 0x2a, 0xa0,
	0x14, 0x27, 0x71, 0xee, 0x4a, 0x8a, 0xe8, 0x08, 0x5a, 0x2f, 0x13, 0x92, 0xad, 0xd2, 0xbe, 0x3e,
	0x30, 0x86, 0xb6, 0x9f, 0x4b, 0x68, 0x08, 0x66, 0x4a, 0x03, 0x8a, 0xfb, 0xc6, 0x40, 0x1b, 0xf6,
	0x46, 0xe8, 0x44, 0x46, 0xce, 0xfc, 0x5e, 0x30, 0x8d, 0x2f, 0x0e, 0x78, 0xff, 0x68, 0xb0, 0x57,
	0xde, 0xb7, 0x5a, 0xac, 0xd1, 0xc7, 0x60, 0xb2, 0x48, 0xd3, 0xbe, 0x36, 0x30, 0x86, 0x9d, 0xd1,
	0xed, 0xc2, 0xb6, 0x72, 0x8c, 0x7b, 0xf2, 0xc5, 0x49, 0x77, 0x05, 0x4d, 0x26, 0x32, 0x60, 0x0a,
	0x60, 0xbe, 0x2e, 0x43, 0xd1, 0xdf, 0x10, 0x0a, 0xb3, 0xbe, 0x26, 0xb3, 0xb4, 0x6f, 0x0c, 0x8c,
	0xa1, 0xe9, 0xf3, 0xb5, 0x02, 0xb0, 0xa9, 0x02, 0xf4, 0x7e, 0xd3, 0xa0, 0x37, 0xc1, 0x74, 0x4a,
	0x66, 0x05, 0x4b, 0x67, 0xd0, 0xbe, 0x26, 0xb3, 0xcb, 0x28, 0x94, 0x91, 0xbf, 0xa7, 0x46, 0xae,
	0x9c, 0x3c, 0x99, 0x92, 0xd9, 0xd3, 0x30, 0x3d, 0x8f, 0x69, 0xb2, 0xf6, 0x5b, 0xd7, 0x5c, 0x70,
	0x3f, 0x81, 0x8e, 0xb2, 0x8d, 0x1c, 0x30, 0x5e, 0xe1, 0x35, 0x07, 0x62, 0xfa, 0x6c, 0x89, 0x0e,
	0xc1, 0xfc, 0x39, 0x58, 0x64, 0x02, 0x87, 0xe5, 0x0b, 0xe1, 0xa1, 0x7e, 0xaa, 0x79, 0x7f, 0x6b,
	0x60, 0x4c, 0xc9, 0x0c, 0xf5, 0x40, 0x8f, 0xc2, 0xdc, 0x44, 0x8f, 0x42, 0x96, 0xb6, 0x39, 0x59,
	0x2e, 0x83, 0x38, 0xcc, 0x33, 0x2d, 0x45, 0xe6, 0x4b, 0x50, 0x6c, 0x70, 0x50, 0x42, 0x40, 0xef,
	0x42, 0x67, 0x9e, 0xe0, 0x80, 0xe2, 0x4b, 0x1a, 0x2d, 0x71, 0xbf, 0x39, 0xd0, 0x86, 0x86, 0x0f,
	0x62, 0xeb, 0x79, 0xb4, 0xc4, 0xe8, 0x18, 0x2c, 0x1c, 0x87, 0x42, 0x6b, 0x72, 0x6d, 0x1b, 0xc7,
	0x21, 0x57, 0xdd, 0x95, 0x2c, 0xb7, 0x38, 0xcb, 0x07, 0x05, 0xf4, 0x29, 0x99, 0x55, 0xf2, 0x7d,
	0x1f, 0xba, 0x05, 0x1b, 0x2c, 0xdb, 0x83, 0x9c, 0x74, 0x41, 0x59, 0x57, 0xb5, 0x13, 0x29, 0xf0,
	0x3e, 0x03, 0x67, 0x82, 0xe9, 0x37, 0x19, 0x5d, 0x65, 0xc5, 0xeb, 0xbe, 0x09, 0x2d, 0xc1, 0x75,
	0x0e, 0xd7, 0xe4, 0x2c, 0xf2, 0xfc, 0x93, 0x10, 0xcb, 0x87, 0xcd, 0xd6, 0xde, 0x73, 0x9e, 0x28,
	0x69, 0xce, 0xae, 0x94, 0xa7, 0xb4, 0xf2, 0x14, 0xcb, 0x73, 0x4a, 0x43, 0x92, 0xc9, 0xa2, 0xc8,
	0xa5, 0x7c, 0x1f, 0x27, 0x09, 0x7f, 0xc9, 0x62, 0x1f, 0x27, 0x89, 0x97, 0xc1, 0x8d, 0x0b, 0x1a,
	0x24, 0x74, 0xbc, 0xc8, 0x52, 0x16, 0x6a, 0x59, 0x29, 0x92, 0x72, 0x6d, 0x07, 0xe5, 0xba, 0x4a,
	0xb9, 0x52, 0x59, 0x46, 0xb5, 0xb2, 0x0e, 0xc1, 0xe4, 0x4f, 0x8d, 0xa7, 0xc1, 0xf6, 0x85, 0xe0,
	0xfd, 0xa5, 0xc1, 0x41, 0xf5, 0x5e, 0x06, 0x68, 0x07, 0x1b, 0xdb, 0xaf, 0x94, 0xe8, 0x8d, 0xad,
	0xe8, 0x9b, 0x3b, 0xd0, 0x9b, 0x2a, 0x7a, 0x74, 0x1b, 0x6c, 0xfc, 0x6b, 0x44, 0x2f, 0xe7, 0xcc,
	0x11, 0xcb, 0xf8, 0x81, 0x6f, 0xb1, 0x8d, 0x31, 0x23, 0xfc, 0x43, 0x38, 0x1c, 0x07, 0xf1, 0x1c,
	0x2f, 0x6a, 0xdc, 0x6c, 0x8f, 0xd2, 0xfb, 0x11, 0xf6, 0x39, 0x22, 0xe5, 0xa4, 0x0b, 0xd6, 0x15,
	0x0e, 0x42, 0x25, 0x49, 0x85, 0xac, 0x78, 0xd1, 0x55, 0xac, 0x0a, 0xf1, 0x46, 0x85, 0x78, 0xef,
	0x07, 0xd8, 0x2b, 0xfd, 0x33, 0xb6, 0x4a, 0xb0, 0xda, 0x0e, 0xb0, 0xfa, 0x6e, 0xb0, 0x46, 0x0d,
	0xec, 0xf7, 0xe0, 0x08, 0xb0, 0x6f, 0x17, 0xfe, 0x21, 0x98, 0x2f, 0x48, 0x32, 0x17, 0xfe, 0x2d,
	0x5f, 0x08, 0xde, 0x53, 0xd8, 0xff, 0x2e, 0x58, 0x44, 0x21, 0x2b, 0x9f, 0xff, 0xe1, 0xdb, 0x05,
	0x8b, 0x55, 0x8f, 0x52, 0x01, 0x85, 0xec, 0x7d, 0x00, 0x7b, 0xa5, 0x2b, 0xc6, 0xc2, 0x6b, 0xe6,
	0x83, 0xf7, 0x00, 0x6e, 0x5c, 0x60, 0xfa, 0x24, 0xf7, 0x5b, 0x34, 0xb8, 0x3b, 0x60, 0xcb, 0xbb,
	0x44, 0xbd, 0xda, 0x7e, 0xb9, 0xe1, 0xfd, 0xce, 0x9e, 0x66, 0xc5, 0x8a, 0x5d, 0xf3, 0x05, 0xb4,
	0x13, 0x9c, 0x66, 0x0b, 0x2a, 0x2b, 0xfc, 0x6e, 0x51, 0xe1, 0x1b, 0x87, 0x4f, 0x7c, 0x71, 0x52,
	0x34, 0x46, 0x69, 0xe7, 0x3e, 0x84, 0xae, 0xaa, 0x50, 0x5b, 0xa3, 0xbd, 0xa5, 0x35, 0xda, 0x6a,
	0x6b, 0xfc, 0x53, 0x83, 0x83, 0xc9, 0x46, 0x50, 0x93, 0x3a, 0x90, 0xce, 0xe8, 0x7d, 0xb5, 0x57,
	0xd7, 0xc2, 0x2a, 0x44, 0x11, 0x58, 0x69, 0xeb, 0x9e, 0x41, 0xaf, 0xaa, 0x7c, 0x53, 0x70, 0x6a,
	0xdf, 0xbe, 0x77, 0x0a, 0x76, 0x31, 0x83, 0x50, 0x07, 0xda, 0xdf, 0xc6, 0xaf, 0x62, 0xf2, 0x4b,
	0xec, 0x34, 0x90, 0x0d, 0xa6, 0x8f, 0x83, 0x70, 0xed, 0x68, 0x6c, 0x79, 0x9e, 0x24, 0x24, 0x71,
	0x74, 0x64, 0x41, 0xf3, 0x19, 0x49, 0xa9, 0x63, 0xdc, 0x5b, 0x80, 0x25, 0xfb, 0x2a, 0x33, 0x1c,
	0xf3, 0x16, 0x1d, 0x3a, 0x0d, 0xb4, 0x0f, 0x9d, 0xaf, 0xa2, 0x74, 0x15, 0xd0, 0xf9, 0x55, 0x14,
	0xbf, 0x74, 0x34, 0xa6, 0xf5, 0xb3, 0x38, 0x66, 0x82, 0x8e, 0xf6, 0xc0, 0x16, 0x8f, 0x95, 0x89,
	0x06, 0xea, 0x82, 0xf5, 0x38, 0x8a, 0xa3, 0xf4, 0x0a, 0x87, 0x4e, 0x13, 0x01, 0xb4, 0x1e, 0x07,
	0xd1, 0x02, 0x87, 0x8e, 0xc9, 0x34, 0xe2, 0x20, 0x0e, 0x9d, 0xd6, 0xe8, 0x0f, 0x03, 0x2c, 0x09,
	0x13, 0x9d, 0x82, 0x5d, 0xfc, 0x35, 0xd0, 0x71, 0xc1, 0x5a, 0xfd, 0xff, 0xe1, 0xf6, 0x0a, 0x95,
	0xf8, 0x56, 0x34, 0xd0, 0xe7, 0x60, 0xc9, 0x09, 0x8e, 0xfa, 0x5b, 0x86, 0xba, 0xb0, 0x3b, 0xda,
	0x3e, 0xee, 0xbd, 0x06, 0xfa, 0x14, 0xda, 0xf9, 0xe4, 0x40, 0xb7, 0x76, 0x4c, 0x56, 0xf7, 0xe6,
	0xa6, 0x42, 0x18, 0x8f, 0xc1, 0x2e, 0xa6, 0x80, 0x12, 0x76, 0x7d, 0xb0, 0xb8, 0xb7, 0xb6, 0xa9,
	0xb8, 0x8b, 0xfb, 0x1a, 0x7a, 0x06, 0x5d, 0xb5, 0xf9, 0xa2, 0x3b, 0xe5, 0x5b, 0xde, 0x9c, 0x05,
	0xae, 0xbb, 0x43, 0x2b, 0xbd, 0x3d, 0x82, 0xbd, 0x4a, 0x9f, 0x44, 0xef, 0x14, 0x06, 0xdb, 0xfa,
	0xe7, 0x26, 0xa3, 0xa3, 0x7f, 0x75, 0xb0, 0xc6, 0x79, 0x85, 0xa3, 0x47, 0x60, 0xc9, 0x3e, 0xa7,
	0xd0, 0x5b, 0x6b, 0xad, 0x0a, 0xbd, 0x95, 0xa6, 0xc8, 0x03, 0x3a, 0x95, 0xcf, 0x83, 0xb9, 0x38,
	0xae, 0x05, 0xf3, 0xba, 0x40, 0x58, 0x6a, 0x65, 0x77, 0x51, 0xee, 0xae, 0xf5, 0x2e, 0xe5, 0xee,
	0x4a, 0x2b, 0xf2, 0x1a, 0x68, 0x0a, 0x5d, 0xb5, 0x1b, 0xa8, 0xc4, 0x6e, 0xf6, 0x21, 0x95, 0xd8,
	0x7a, 0xad, 0x7a, 0x0d, 0x74, 0xc6, 0x3f, 0x18, 0xa5, 0xaf, 0x5a, 0xb4, 0x8a, 0xf5, 0x64, 0xd3,
	0x7a, 0xd6, 0xe2, 0x5f, 0xeb, 0x07, 0xff, 0x05, 0x00, 0x00, 0xff, 0xff, 0x81, 0x36, 0x3d, 0x0f,
	0x74, 0x0b, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// HeadnodeClient is the client API for Headnode service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type HeadnodeClient interface {
	Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*Empty, error)
	GetNodes(ctx context.Context, in *GetNodesRequest, opts ...grpc.CallOption) (*GetNodesReply, error)
	GetJobs(ctx context.Context, in *GetJobsRequest, opts ...grpc.CallOption) (*GetJobsReply, error)
	GetOutput(ctx context.Context, in *GetOutputRequest, opts ...grpc.CallOption) (Headnode_GetOutputClient, error)
	StartClusJob(ctx context.Context, in *StartClusJobRequest, opts ...grpc.CallOption) (Headnode_StartClusJobClient, error)
	CancelClusJob(ctx context.Context, in *CancelClusJobRequest, opts ...grpc.CallOption) (*Empty, error)
}

type headnodeClient struct {
	cc *grpc.ClientConn
}

func NewHeadnodeClient(cc *grpc.ClientConn) HeadnodeClient {
	return &headnodeClient{cc}
}

func (c *headnodeClient) Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/clusrun.Headnode/Heartbeat", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *headnodeClient) GetNodes(ctx context.Context, in *GetNodesRequest, opts ...grpc.CallOption) (*GetNodesReply, error) {
	out := new(GetNodesReply)
	err := c.cc.Invoke(ctx, "/clusrun.Headnode/GetNodes", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *headnodeClient) GetJobs(ctx context.Context, in *GetJobsRequest, opts ...grpc.CallOption) (*GetJobsReply, error) {
	out := new(GetJobsReply)
	err := c.cc.Invoke(ctx, "/clusrun.Headnode/GetJobs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *headnodeClient) GetOutput(ctx context.Context, in *GetOutputRequest, opts ...grpc.CallOption) (Headnode_GetOutputClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Headnode_serviceDesc.Streams[0], "/clusrun.Headnode/GetOutput", opts...)
	if err != nil {
		return nil, err
	}
	x := &headnodeGetOutputClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Headnode_GetOutputClient interface {
	Recv() (*GetOutputReply, error)
	grpc.ClientStream
}

type headnodeGetOutputClient struct {
	grpc.ClientStream
}

func (x *headnodeGetOutputClient) Recv() (*GetOutputReply, error) {
	m := new(GetOutputReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *headnodeClient) StartClusJob(ctx context.Context, in *StartClusJobRequest, opts ...grpc.CallOption) (Headnode_StartClusJobClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Headnode_serviceDesc.Streams[1], "/clusrun.Headnode/StartClusJob", opts...)
	if err != nil {
		return nil, err
	}
	x := &headnodeStartClusJobClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Headnode_StartClusJobClient interface {
	Recv() (*StartClusJobReply, error)
	grpc.ClientStream
}

type headnodeStartClusJobClient struct {
	grpc.ClientStream
}

func (x *headnodeStartClusJobClient) Recv() (*StartClusJobReply, error) {
	m := new(StartClusJobReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *headnodeClient) CancelClusJob(ctx context.Context, in *CancelClusJobRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/clusrun.Headnode/CancelClusJob", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HeadnodeServer is the server API for Headnode service.
type HeadnodeServer interface {
	Heartbeat(context.Context, *HeartbeatRequest) (*Empty, error)
	GetNodes(context.Context, *GetNodesRequest) (*GetNodesReply, error)
	GetJobs(context.Context, *GetJobsRequest) (*GetJobsReply, error)
	GetOutput(*GetOutputRequest, Headnode_GetOutputServer) error
	StartClusJob(*StartClusJobRequest, Headnode_StartClusJobServer) error
	CancelClusJob(context.Context, *CancelClusJobRequest) (*Empty, error)
}

// UnimplementedHeadnodeServer can be embedded to have forward compatible implementations.
type UnimplementedHeadnodeServer struct {
}

func (*UnimplementedHeadnodeServer) Heartbeat(ctx context.Context, req *HeartbeatRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Heartbeat not implemented")
}
func (*UnimplementedHeadnodeServer) GetNodes(ctx context.Context, req *GetNodesRequest) (*GetNodesReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNodes not implemented")
}
func (*UnimplementedHeadnodeServer) GetJobs(ctx context.Context, req *GetJobsRequest) (*GetJobsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetJobs not implemented")
}
func (*UnimplementedHeadnodeServer) GetOutput(req *GetOutputRequest, srv Headnode_GetOutputServer) error {
	return status.Errorf(codes.Unimplemented, "method GetOutput not implemented")
}
func (*UnimplementedHeadnodeServer) StartClusJob(req *StartClusJobRequest, srv Headnode_StartClusJobServer) error {
	return status.Errorf(codes.Unimplemented, "method StartClusJob not implemented")
}
func (*UnimplementedHeadnodeServer) CancelClusJob(ctx context.Context, req *CancelClusJobRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CancelClusJob not implemented")
}

func RegisterHeadnodeServer(s *grpc.Server, srv HeadnodeServer) {
	s.RegisterService(&_Headnode_serviceDesc, srv)
}

func _Headnode_Heartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HeadnodeServer).Heartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/clusrun.Headnode/Heartbeat",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HeadnodeServer).Heartbeat(ctx, req.(*HeartbeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Headnode_GetNodes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNodesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HeadnodeServer).GetNodes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/clusrun.Headnode/GetNodes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HeadnodeServer).GetNodes(ctx, req.(*GetNodesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Headnode_GetJobs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetJobsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HeadnodeServer).GetJobs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/clusrun.Headnode/GetJobs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HeadnodeServer).GetJobs(ctx, req.(*GetJobsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Headnode_GetOutput_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetOutputRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(HeadnodeServer).GetOutput(m, &headnodeGetOutputServer{stream})
}

type Headnode_GetOutputServer interface {
	Send(*GetOutputReply) error
	grpc.ServerStream
}

type headnodeGetOutputServer struct {
	grpc.ServerStream
}

func (x *headnodeGetOutputServer) Send(m *GetOutputReply) error {
	return x.ServerStream.SendMsg(m)
}

func _Headnode_StartClusJob_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StartClusJobRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(HeadnodeServer).StartClusJob(m, &headnodeStartClusJobServer{stream})
}

type Headnode_StartClusJobServer interface {
	Send(*StartClusJobReply) error
	grpc.ServerStream
}

type headnodeStartClusJobServer struct {
	grpc.ServerStream
}

func (x *headnodeStartClusJobServer) Send(m *StartClusJobReply) error {
	return x.ServerStream.SendMsg(m)
}

func _Headnode_CancelClusJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelClusJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HeadnodeServer).CancelClusJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/clusrun.Headnode/CancelClusJob",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HeadnodeServer).CancelClusJob(ctx, req.(*CancelClusJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Headnode_serviceDesc = grpc.ServiceDesc{
	ServiceName: "clusrun.Headnode",
	HandlerType: (*HeadnodeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Heartbeat",
			Handler:    _Headnode_Heartbeat_Handler,
		},
		{
			MethodName: "GetNodes",
			Handler:    _Headnode_GetNodes_Handler,
		},
		{
			MethodName: "GetJobs",
			Handler:    _Headnode_GetJobs_Handler,
		},
		{
			MethodName: "CancelClusJob",
			Handler:    _Headnode_CancelClusJob_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetOutput",
			Handler:       _Headnode_GetOutput_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StartClusJob",
			Handler:       _Headnode_StartClusJob_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "protobuf/clusrun.proto",
}

// ClusnodeClient is the client API for Clusnode service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ClusnodeClient interface {
	StartJob(ctx context.Context, in *StartJobRequest, opts ...grpc.CallOption) (Clusnode_StartJobClient, error)
	CancelJob(ctx context.Context, in *CancelJobRequest, opts ...grpc.CallOption) (*Empty, error)
	Validate(ctx context.Context, in *ValidateRequest, opts ...grpc.CallOption) (*ValidateReply, error)
	SetHeadnodes(ctx context.Context, in *SetHeadnodesRequest, opts ...grpc.CallOption) (*SetHeadnodesReply, error)
	GetHeadnodes(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GetHeadnodesReply, error)
}

type clusnodeClient struct {
	cc *grpc.ClientConn
}

func NewClusnodeClient(cc *grpc.ClientConn) ClusnodeClient {
	return &clusnodeClient{cc}
}

func (c *clusnodeClient) StartJob(ctx context.Context, in *StartJobRequest, opts ...grpc.CallOption) (Clusnode_StartJobClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Clusnode_serviceDesc.Streams[0], "/clusrun.Clusnode/StartJob", opts...)
	if err != nil {
		return nil, err
	}
	x := &clusnodeStartJobClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Clusnode_StartJobClient interface {
	Recv() (*StartJobReply, error)
	grpc.ClientStream
}

type clusnodeStartJobClient struct {
	grpc.ClientStream
}

func (x *clusnodeStartJobClient) Recv() (*StartJobReply, error) {
	m := new(StartJobReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *clusnodeClient) CancelJob(ctx context.Context, in *CancelJobRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/clusrun.Clusnode/CancelJob", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clusnodeClient) Validate(ctx context.Context, in *ValidateRequest, opts ...grpc.CallOption) (*ValidateReply, error) {
	out := new(ValidateReply)
	err := c.cc.Invoke(ctx, "/clusrun.Clusnode/Validate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clusnodeClient) SetHeadnodes(ctx context.Context, in *SetHeadnodesRequest, opts ...grpc.CallOption) (*SetHeadnodesReply, error) {
	out := new(SetHeadnodesReply)
	err := c.cc.Invoke(ctx, "/clusrun.Clusnode/SetHeadnodes", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clusnodeClient) GetHeadnodes(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GetHeadnodesReply, error) {
	out := new(GetHeadnodesReply)
	err := c.cc.Invoke(ctx, "/clusrun.Clusnode/GetHeadnodes", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ClusnodeServer is the server API for Clusnode service.
type ClusnodeServer interface {
	StartJob(*StartJobRequest, Clusnode_StartJobServer) error
	CancelJob(context.Context, *CancelJobRequest) (*Empty, error)
	Validate(context.Context, *ValidateRequest) (*ValidateReply, error)
	SetHeadnodes(context.Context, *SetHeadnodesRequest) (*SetHeadnodesReply, error)
	GetHeadnodes(context.Context, *Empty) (*GetHeadnodesReply, error)
}

// UnimplementedClusnodeServer can be embedded to have forward compatible implementations.
type UnimplementedClusnodeServer struct {
}

func (*UnimplementedClusnodeServer) StartJob(req *StartJobRequest, srv Clusnode_StartJobServer) error {
	return status.Errorf(codes.Unimplemented, "method StartJob not implemented")
}
func (*UnimplementedClusnodeServer) CancelJob(ctx context.Context, req *CancelJobRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CancelJob not implemented")
}
func (*UnimplementedClusnodeServer) Validate(ctx context.Context, req *ValidateRequest) (*ValidateReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Validate not implemented")
}
func (*UnimplementedClusnodeServer) SetHeadnodes(ctx context.Context, req *SetHeadnodesRequest) (*SetHeadnodesReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetHeadnodes not implemented")
}
func (*UnimplementedClusnodeServer) GetHeadnodes(ctx context.Context, req *Empty) (*GetHeadnodesReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetHeadnodes not implemented")
}

func RegisterClusnodeServer(s *grpc.Server, srv ClusnodeServer) {
	s.RegisterService(&_Clusnode_serviceDesc, srv)
}

func _Clusnode_StartJob_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StartJobRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ClusnodeServer).StartJob(m, &clusnodeStartJobServer{stream})
}

type Clusnode_StartJobServer interface {
	Send(*StartJobReply) error
	grpc.ServerStream
}

type clusnodeStartJobServer struct {
	grpc.ServerStream
}

func (x *clusnodeStartJobServer) Send(m *StartJobReply) error {
	return x.ServerStream.SendMsg(m)
}

func _Clusnode_CancelJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClusnodeServer).CancelJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/clusrun.Clusnode/CancelJob",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClusnodeServer).CancelJob(ctx, req.(*CancelJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Clusnode_Validate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClusnodeServer).Validate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/clusrun.Clusnode/Validate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClusnodeServer).Validate(ctx, req.(*ValidateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Clusnode_SetHeadnodes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetHeadnodesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClusnodeServer).SetHeadnodes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/clusrun.Clusnode/SetHeadnodes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClusnodeServer).SetHeadnodes(ctx, req.(*SetHeadnodesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Clusnode_GetHeadnodes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClusnodeServer).GetHeadnodes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/clusrun.Clusnode/GetHeadnodes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClusnodeServer).GetHeadnodes(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _Clusnode_serviceDesc = grpc.ServiceDesc{
	ServiceName: "clusrun.Clusnode",
	HandlerType: (*ClusnodeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CancelJob",
			Handler:    _Clusnode_CancelJob_Handler,
		},
		{
			MethodName: "Validate",
			Handler:    _Clusnode_Validate_Handler,
		},
		{
			MethodName: "SetHeadnodes",
			Handler:    _Clusnode_SetHeadnodes_Handler,
		},
		{
			MethodName: "GetHeadnodes",
			Handler:    _Clusnode_GetHeadnodes_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StartJob",
			Handler:       _Clusnode_StartJob_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "protobuf/clusrun.proto",
}
